version: "3.8"
services:
  qstash:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qstash
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"